# Generated by Django 3.2.3 on 2022-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.IntegerField()),
                ('user_Id', models.IntegerField()),
                ('upvote_User', models.IntegerField()),
                ('downvote_User', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
    ]
